repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.6.0
    hooks:
      - id: markdownlint-cli2
