[project]
name = "diploma-thesis"
requires-python = "==3.13.2"
version = "0.1.0"

[tool.poetry]
package-mode = false
requires-poetry = "2.1.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "4.1.0"
