name: ci
on: [pull_request, push, workflow_dispatch]
permissions: {}
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: pipx install poetry==1.4.2
      - id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
      - run: poetry install
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-python-${{ steps.setup-python.outputs.python-version }}
            pre-commit
      - id: pre-commit
        run: poetry run pre-commit run --all-files --color=always --show-diff-on-failure
      - if: success() || failure() && steps.pre-commit.outcome == 'failure'
        run: poetry run pytest --color=yes
