name: ci
on: [pull_request, push, workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: pipx install poetry==1.4.2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
